name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: mkdir compiled_rpms
      - name: rpmbuild
        uses: ./.github/actions/rpmbuild/
        #uses: robertdebock/rpmbuild-action@1.1.1
      - uses: actions/upload-artifact@v1
        with:
          name: RPMs
          path: ./compiled_rpms
