name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rpmbuild
        uses: ./.github/actions/rpmbuild/
      - run: ls
        #uses: robertdebock/rpmbuild-action@1.1.1
